src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/components/Signin/GeneralSiginForm/GeneralSigninForm.tsx, src/app/components/Signin/OutlinedSigningForm/OutlinedSigningForm.tsx, src/app/components/Signin/SigninFormWithSocialButton/SigninFormWithSocialButton.tsx, src/app/components/Signin/StandardSigninForm/StandardSigninForm.tsx, src/app/signin/page.tsx
=> [Task-22]-Create SignIn components

src/app/components/Signin/GeneralSiginForm/GeneralSigninForm.tsx, src/app/components/Signin/OutlinedSigningForm/OutlinedSigningForm.tsx, src/app/components/Signin/StandardSigninForm/StandardSigninForm.tsx
=> [Bug-24]-Bug - Sign-in issues

src/app/components/Ecommerce/AddNewProduct.tsx
Bug - Issues in add new product page
=> [Bug-29]-Bug - Issues in add new product page

src/app/components/Ecommerce/Order.tsx
Bug - UI issues in orders page
=> [Bug-30]-Bug - UI issues in orders page

src/app/components/Ecommerce/AddProductModal.tsx, src/app/components/Ecommerce/DeleteModal.tsx, src/app/components/Ecommerce/EditProductModal.tsx, src/app/components/Ecommerce/ProductData.tsx, src/app/components/Ecommerce/ProductsListHeader.tsx, src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/ecommerce/product-list/page.tsx, src/product-data.json
[Bug-27]-Bug - Issues in Products page
=> [Bug-27]-Bug - Issues in Products page

src/app/components/Ecommerce/ProductDetailTabs.tsx, src/app/components/Ecommerce/ProductDetails.tsx, src/app/components/Ecommerce/RelatedProducts.tsx, src/app/components/Ecommerce/ReviewCommentForm.tsx, src/app/ecommerce/add-new-product/page.tsx, src/app/ecommerce/order/page.tsx, src/app/ecommerce/product-details/page.tsx, src/app/ecommerce/product-list/page.tsx, src/app/ecommerce/products/page.tsx, src/app/globals.css
Bug - Issues in Product details page
=> [Bug-28]-Bug - Issues in Product details page

src/app/components/ImportExportElement/DataTable.tsx, src/app/components/ImportExportElement/ImportElement.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/globals.css
Bug - Validation issue in import feature
=> [Bug-32]-Bug - Validation issue in import feature

src/app/components/Ecommerce/ProductDetails.tsx, src/app/components/Ecommerce/WishlistItem.tsx, src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/ecommerce/wishlist/page.tsx, src/app/globals.css
=> [Task-31]-Create wishlist page

src/app/components/AlertElement/AlertElement.tsx, src/app/components/AlertElement/AlertWithCloseButton.tsx, src/app/components/AlertElement/BasicAlert.tsx, src/app/components/ButtonElement/BasicButtonElement.tsx, src/app/components/ButtonElement/ButtonElement.tsx, src/app/components/ButtonElement/ButtonWithIcon.tsx, src/app/components/ButtonElement/GroupButton.tsx, src/app/components/ButtonElement/OutlineButtonElement.tsx, src/app/components/ModalsElement/ModalsElement.tsx, src/app/components/NavbarElement/NavbarElement.tsx, src/app/components/TabsElement/BasicTab.tsx, src/app/components/TabsElement/TabWithIcon.tsx, src/app/components/TabsElement/TabsElement.tsx, src/app/globals.css
Admina Theme- UI elements changes
=> [Task-33]-Admina Theme- UI elements changes

src/app/components/Ecommerce/ProductDetails.tsx, src/app/components/Ecommerce/ProductList.tsx, src/app/globals.css
=> [Bug-35]-Bug - Issues in wishlist page

src/app/components/Crud/CreateData.tsx, src/app/components/Crud/Deletemodal.tsx, src/app/components/Crud/EditData.tsx, src/app/components/Crud/List.tsx, src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/crud/add/page.tsx, src/app/crud/edit/[sno]/page.tsx, src/app/crud/list/page.tsx, src/app/globals.css, src/data-table.json
Implement table CRUD components and pages
=> [Task-26]-Implement table CRUD components and pages

src/app/components/Crud/CreateData.tsx, src/app/components/Crud/List.tsx, src/app/globals.css
Bug - Issues in table crud component
=> [Bug-38]-Bug - Issues in table crud component

src/app/components/Ecommerce/ProductDetails.tsx, src/app/components/Login/Login.tsx, src/app/components/Login/Signup.tsx, src/app/globals.css
=> [Bug-39]-Bug - Issues in login page

src/app/components/BasicWithIcon/BasicWithIcon.tsx, src/app/components/FormGrid/FormGrid.tsx, src/app/components/Header/Header.tsx, src/app/components/HorizontalForm/HorizontalForm.tsx, src/app/components/HorizontalFormWithIcon/HorizontalFormWithIcon.tsx, src/app/components/NavbarElement/NavbarElement.tsx
=> [Bug-44]-Bug - Issues in forms page

src/app/components/Login/Login.tsx, src/app/layout.tsx
Bug - Issues in Login page template
=> [Bug-46]-Bug - Issues in Login page template

src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/components/SubscriptionPlan/BasicSubscriptionPlan.tsx, src/app/components/SubscriptionPlan/SubscriptionPlan.tsx, src/app/components/SubscriptionPlan/SubscriptionPlanCard.tsx, src/app/subscription-plan/page.tsx, src/subscription-plan.json
Implement subscription plan based feature
=> [Task-42]-Implement subscription plan based feature

src/app/components/Header/Header.tsx, src/app/components/NavbarElement/NavbarElement.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/components/SubscriptionPlan/SubscriptionPlanCard.tsx
Bug - UI issues in subscription plan
=> [Task-47]-Bug - UI issues in subscription plan

src/app/components/Crud/CreateData.tsx, src/app/components/Crud/EditData.tsx, src/app/components/Crud/List.tsx
Changes-in-CRUD-list-page-and-create-page
=> [Task-50]-Changes-in-CRUD-list-page-and-create-page

src/app/components/Crud/CreateData.tsx, src/app/components/Crud/EditData.tsx, src/app/components/Crud/List.tsx, src/crud-table.json
Bug - Search and form fields issues in crud list page
=> [Bug-52]-Bug - Search and form fields issues in crud list page

src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx, src/app/globals.css
=> [Bug-54]-Bug - Issues in submenus 

src/app/components/Crud/CreateData.tsx, src/app/components/Crud/EditData.tsx
=> Changed Placeholder Name

src/app/components/Header/Header.tsx, src/app/components/Sidebar/Sidebar.tsx
Bug - Menu shrinks when clicking submenu
=> [Bug-56]-Bug - Menu shrinks when clicking submenu

src/app/components/Notification/NotificationItem.tsx
Bug - New notifications delete issue after click the delete icon
=> [Bug-64]-Bug - New notifications delete issue after click delete icon

src/app/components/Accounts/AccountSetting.tsx, src/app/components/Accounts/Accounts.tsx, src/app/components/Accounts/BillingSetting.tsx, src/app/components/Accounts/PasswordSetting.tsx, src/app/components/Accounts/PaymentMethods.tsx
Bug -  Need to add a mandatory symbol and UI issues
=> [Bug-66]-Bug -  Need to add mandatory symbol and UI issues

src/app/components/Calendar/EventCalendar.tsx, src/app/components/Header/Header.tsx
=> [Bug-65]-Bug - Issues in calendar

src/app/components/Notification/NotficationList.tsx
Implement clearall option in notifications
=> [Task-67]-Implement clearall option in notifications

src/app/components/NotificationDetails/Notification.css, src/app/components/NotificationDetails/Notifications.tsx, src/app/notifications/page.tsx
UI issues in notifications page
=> [Bug-703]-UI issues in notifications page

src/app/components/AdvancedKanbanBoard/AddColumn.tsx, src/app/components/AdvancedKanbanBoard/AddTask.tsx, src/app/components/AdvancedKanbanBoard/AdvancedKanbanBoard.tsx, src/app/components/AdvancedKanbanBoard/ColumnHeader.tsx, src/app/components/AdvancedKanbanBoard/EditTask.tsx, src/app/components/AdvancedKanbanBoard/Task.tsx, src/app/components/AdvancedKanbanBoard/columns.json, src/app/components/AdvancedKanbanBoard/tasks.json, src/app/components/AdvancedKanbanBoard/users.json, src/app/components/KanbanBoardswimlane/AddStatus.tsx, src/app/components/KanbanBoardswimlane/AddTask.tsx, src/app/components/KanbanBoardswimlane/EditTask.tsx, src/app/components/KanbanBoardswimlane/KanbanBoard.tsx, src/app/components/KanbanBoardswimlane/Task.tsx, src/app/components/KanbanBoardswimlane/tasks.json, src/app/components/Sidebar/Sidebar.tsx, src/app/kanban-board/with-collapse/page.tsx, src/app/layout.tsx
=> Fixed UI issues in kanban board in 705 and 711 

src/app/components/ScrollBar/HorizondalScrollbar.tsx, src/app/components/ScrollBar/VerticalAndHorizondalScrollbar.tsx, src/app/components/ScrollBar/VerticalScrollbar.tsx, src/app/components/Sidebar/menuItems.ts, src/app/uielements/scroll-bar/page.tsx
Need to change page name scroll bar instead of navbar
=> [Bug-739]-Need to change page name scroll bar instead of navbar

src/app/components/Header/Header.tsx
Change placeholder and reset functionality in search box
=> [Bug-738]-Change placeholder and reset functionality in search box

src/app/components/ModalForms/CheckboxModalForm.tsx, src/app/components/ModalForms/ComplexModalForm.tsx, src/app/components/ModalForms/ContactDetailsForm.tsx, src/app/components/ModalForms/LeftSideComponent.tsx, src/app/components/ModalForms/ModalButtonComponent.tsx, src/app/components/ModalForms/PersonalDetailsForm.tsx, src/app/components/ModalForms/RightSideComponent.tsx, src/app/components/ModalForms/SectionModalForm.tsx
Reset and UI issue in modal forms
=> [Bug-741]-Reset and UI issue in modal forms

src/app/components/Sidebar/menuItems.ts, src/app/components/TransferList/BasicTransferList.tsx, src/app/components/TransferList/EnchancedTransferlist.tsx, src/app/components/TransferList/TransferListwithIcon.tsx, src/app/components/TransferList/list.json, src/app/uielements/transfer-list/page.tsx
=> [Task-747]-IImplement Transfer list

src/app/components/Calendar/AddEvent.tsx, src/app/components/Calendar/UpdateEvent.tsx, src/app/components/DragAndDrop/DragAndDropContext.tsx, src/app/components/DragAndDrop/DraggableCard.tsx, src/app/components/DragAndDrop/DraggableList.tsx, src/app/components/DragAndDrop/SortableList.tsx, src/app/components/Ecommerce/AddNewProduct.tsx, src/app/components/Ecommerce/AddProductModal.tsx, src/app/components/Ecommerce/ReviewCommentForm.tsx, src/app/components/FormGrid/FormGrid.tsx, src/app/components/HorizontalForm/HorizontalForm.tsx, src/app/components/HorizontalFormWithIcon/HorizontalFormWithIcon.tsx, src/app/components/Signin/OutlinedSigningForm/OutlinedSigningForm.tsx, src/app/components/VerticalForm/VerticalForm.tsx, src/app/drag-and-drop/page.tsx
Mandatory field and UI issues in admina
=> [Bug-751]-Mandatory field and UI issues in admina

src/app/components/ModalForms/AddFiles.tsx, src/app/components/ModalForms/CheckboxModalForm.tsx, src/app/components/ModalForms/ContactDetailsForm.tsx, src/app/components/ModalForms/PersonalDetailsForm.tsx, src/app/components/ModalForms/SectionModalForm.tsx, src/app/globals.css
Alignment and UI issue in section form
=> [Bug-780]-Alignment and UI issue in section form

src/app/components/Carosel/CoverflowEffect.tsx, src/app/components/Carosel/MultiSlides.tsx, src/app/globals.css, src/app/uielements/carousel/page.tsx
Alignment and UI issue in section form
=> [Bug-750]-Alignment and UI issue in section form

src/app/components/AdvancedKanbanBoard/CommentSection.tsx, src/app/components/AdvancedKanbanBoard/EditTask.tsx, src/app/globals.css
Issues with bulleted list icon and comment alignment in advanced kanban board
=> [Bug-846]-Issues with bulleted list icon and comment alignment in advanced kanban board

src/app/components/AdvancedKanbanBoard/CommentSection.tsx
When editing the comments it should open in same editor
=> [Bug-848]-When editing the comments it should open in same editor

src/app/components/AdvancedKanbanBoard/EditTask.tsx
Kanban Board - Clicking remove icon in assignee dropdown is not working
=> [Bug-853]-Kanban Board - Clicking remove icon in assignee dropdown is not working

src/app/components/AdvancedKanbanBoard/CommentSection.tsx
=> [Task-850]-Changes in comment section

src/app/components/AdvancedKanbanBoard/CommentSection.tsx, src/app/components/AdvancedKanbanBoard/EditTask.tsx
Remove unused elements from rich text editor
=> [Task-851]-Remove unused elements from rich text editor
